Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu1404-opsworks"
  config.vm.provision "opsworks", type:"shell", args:"opsworks.json"

  config.vm.network :private_network, type: 'dhcp'

  config.berkshelf.enabled = true
  config.vm.provision :chef_solo do |chef|
    chef.run_list = [
      'recipe[cookbook::default]',
    ]
  end
end
